import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-900 mt-4`}>
        <main className="container m-auto sticky">
          <div className="w-full p-2">
            <div className="flex justify-between">
              {/* Buttons */}
              <div className="flex flex-col ml-4">
                <button className="text-left py-1 px-2 mb-2 bg-indigo-700 rounded-lg text-neutral-100 hover:bg-indigo-800">
                  Resume
                </button>
                <button className="text-left py-1 px-2 bg-indigo-700 rounded-lg text-neutral-100 hover:bg-indigo-800">
                  Blog
                </button>
              </div>
              {/* Sections */}
              <div className="flex flex-col text-right">
                <h2 className="cursor-pointer hover:text-indigo-400">About</h2>
                <h2 className="text-slate-400 cursor-pointer hover:text-indigo-400">
                  Projects
                </h2>
                <h2 className="text-slate-400 cursor-pointer hover:text-indigo-400">
                  Experience
                </h2>
                <h2 className="text-slate-400 cursor-pointer hover:text-indigo-400">
                  Skills
                </h2>
                <h2 className="text-slate-400 cursor-pointer hover:text-indigo-400">
                  Education
                </h2>
                <h2 className="text-slate-400 cursor-pointer hover:text-indigo-400">
                  Contact
                </h2>
              </div>
            </div>
            <div className="relative">{children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
